// <auto-generated />
using System;
using DataVisualization.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataVisualization.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataVisualization.Core.Models.SalesData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SalesData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1200.50m,
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Laptop",
                            Region = "North",
                            Units = 5
                        },
                        new
                        {
                            Id = 2,
                            Amount = 800.25m,
                            Date = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Smartphone",
                            Region = "South",
                            Units = 10
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2400.75m,
                            Date = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Laptop",
                            Region = "East",
                            Units = 8
                        },
                        new
                        {
                            Id = 4,
                            Amount = 650.00m,
                            Date = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Tablet",
                            Region = "West",
                            Units = 7
                        },
                        new
                        {
                            Id = 5,
                            Amount = 950.50m,
                            Date = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Desktop",
                            Region = "North",
                            Units = 3
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1600.75m,
                            Date = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Smartphone",
                            Region = "East",
                            Units = 20
                        },
                        new
                        {
                            Id = 7,
                            Amount = 975.25m,
                            Date = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Tablet",
                            Region = "South",
                            Units = 12
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1900.00m,
                            Date = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Desktop",
                            Region = "West",
                            Units = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
